apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-bankapp # deployment name
  labels:
    app: redis-bankapp # deployment label
spec:
  selector:
    matchLabels:
      app: redis-bankapp # which pods is the deployment managing, as defined by the pod template
  template: # pod template
    metadata:
      labels:
        app: redis-bankapp 
    spec:  
      containers:
      - name:  redis-bankapp  # Container name 
        image: jphaugla/bankapp:fixedconnect #repo/image:tag
        imagePullPolicy: Always # IfNotPresent # Always pull image
        #command: ["/bin/bash"]
        #args: ["-c", "while true; do echo hello; sleep 10;done"]
        args: ["$(REDIS_SERVER)", "$(REDIS_PORT)"]
        env:
          - name: REDIS_SERVER
            value: "172.30.45.103"
            name: REDIS_PORT
            value: "16379"
      resources:
        limits:
            cpu: "1000m"
            memory: "1024Mi"
        requests:
            cpu: "1000m"
            memory: "1024Mi"
        ports:  
         - containerPort: 8080
           protocol: TCP
        
      #  env:
      #    - name: HAPROXY_UPSTREAM_HOSTS
      #      value: "172.30.81.165" #172.30.81.165,172.30.190.110,172.30.161.109
      #    - name: HAPROXY_UPSTREAM_PORT
      #      value: "16379"
          # - name: HAPROXY_STATS_USER
          #   value: "/opt/redislabs/redis-lb/config/logback.xml"
          # - name: HAPROXY_STATS_PASSWORD
          #   value: "/opt/redislabs/redis-lb/config/logback.xml"
              
---
apiVersion: v1
kind: Service
metadata:
  name: redis-bankapp-service       # name should not be 'redis-lb' 
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: redis-bankapp
---
